on: [push, pull_request]
name: CI
jobs:
  build:
    name: "Racket '${{ matrix.racket-version }}' (${{ matrix.racket-variant }}) on ${{ matrix.platform }}"
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        racket-version: ["stable", "current"]
        racket-variant: ["BC", "CS"]
        platform: ["ubuntu-latest", "windows-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v2
      - uses: Bogdanp/setup-racket@v0.12
        with:
          architecture: x64
          distribution: full
          variant: ${{ matrix.racket-variant }}
          version: ${{ matrix.racket-version }}

      - name: Installing openfst native libararies (Linux)
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: raco pkg install -t dir openfst-x86_64-linux/
      - name: Installing openfst native libararies (Windows)
        if: ${{ matrix.platform == 'windows-latest' }}
        run: raco pkg install -t dir openfst-x86_64-win32/
      - if: ${{ matrix.platform == 'macos-latest' }}
        run: raco pkg install -t dir openfst-x86_64-macosx/
        
      - name: Installing openfst
        run: raco pkg install -t dir openfst/
      - name: Compiling openfst and building its docs
        run: raco setup --check-pkg-deps --unused-pkg-deps openfst
      - name: Testing openfst
        run: raco test -p openfst
